externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://solid-pancake.thefirstspine.fr
paths:
  /session:
    post:
      summary: Create a session
      operationId: session
      requestBody:
        content:
          application/json:
            schema:
              required:
                - product
              properties:
                product:
                  type: string
                label:
                  type: string
                version:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
  /event:
    post:
      summary: Create an event
      operationId: event
      requestBody:
        content:
          application/json:
            schema:
              required:
                - sessionId
                - event
              properties:
                sessionId:
                  type: string
                event:
                  type: string
                category:
                  type: string
                action:
                  type: string
                label:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                enum:
                  - ok
                  - er
  /request-stats:
    post:
      summary: Request stats from Solid Pancake
      operationId: request-stats
      requestBody:
        content:
          application/json:
            schema:
              required:
                - type
              properties:
                type:
                  type: string
                  enum:
                    - session
                    - event
                limit:
                  type: integer
                offset:
                  type: integer
                filters:
                  type: object
                  properties:
                    product:
                      type: string
                    version:
                      type: string
                    label:
                      type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
