version: "3.2"

services:
  solid-pancake:
    build: 'solid-pancake'
    image: thefirstspine_solid-pancake_image
    container_name: thefirstspine_solid-pancake_container
    networks:
      default:
    volumes:
      - /var/log:/var/log
    ports:
      - "${PORT}:${PORT}"
    tty: true
    env_file:
      - .env

networks:
  default:
    driver: bridge
