name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: 🚀 Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate timestamp
        id: timestamp
        run: echo "value=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT

      - name: Change to next
        run: git checkout next
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        run: |
          gh pr create --base master --head next --title "Release ${{ steps.timestamp.outputs.value }}" --body "Automated release PR" --fill
          gh pr merge ${{ steps.cpr.outputs.number }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Master
        run: |
          git checkout master
          git pull
          git tag v-${{ steps.timestamp.outputs.value }}
          git push --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}